### PR TITLE
Fix code style problems found by detekt

### LINKED ISSUE #9: Fix detekt errors in generated code
As seen in this CI build:
https://travis-ci.org/kategory/kategory/builds/262477987

- SpacingAfterComma
Example: `typealias CokleisliKind<F,A,B> = kategory.HK3<CokleisliHK, F,A,B>`
Fix: `typealias CokleisliKind<F, A, B> = kategory.HK3<CokleisliHK, F, A, B>`

- UnsafeCast
Example: `fun <A> Function0Kind<A>.ev(): Function0<A> = this as Function0<A>`
Fix: `@Suppress("UNCHECKED_CAST") fun <A> Function0Kind<A>.ev(): Function0<A> = this as Function0<A>`

### PR DESCRIPTION
**Pull request by pakoito**
Closes #9

### CODE REVIEW

File: compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt [hunk 1]
```diff
@@ -16,7 +16,7 @@ data class HigherKind(
     val kindName: Name = target.classElement.simpleName
     val alias: String = if (tparams.size == 1) "kategory.HK" else "kategory.HK${tparams.size}"
     val expandedTypeArgs: String = target.classOrPackageProto.typeParameters.joinToString(
-            separator = ",", transform = { target.classOrPackageProto.nameResolver.getString(it.name) })
+            separator = ", ", transform = { target.classOrPackageProto.nameResolver.getString(it.name) })
```
Comment (raulraja) [inline compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt]: :+1:

File: compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt [hunk 2]
```diff
@@ -51,7 +51,7 @@ class HigherKindsFileGenerator(
     }
 
     private fun genEv(hk: HigherKind): String =
-            "fun <${hk.expandedTypeArgs}> ${hk.name}<${hk.expandedTypeArgs}>.ev(): ${hk.kindName}<${hk.expandedTypeArgs}> = this as ${hk.kindName}<${hk.expandedTypeArgs}>"
+            "@Suppress("UNCHECKED_CAST") fun <${hk.expandedTypeArgs}> ${hk.name}<${hk.expandedTypeArgs}>.ev(): ${hk.kindName}<${hk.expandedTypeArgs}> = this as ${hk.kindName}<${hk.expandedTypeArgs}>"
```
Comment (raulraja) [inline compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt]: this cast is never unchecked. Is this annotation required?

Comment (pakoito) [inline compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt]: Yes, according to detekt: https://travis-ci.org/kategory/kategory/builds/262477987

Comment (raulraja) [inline compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt]: Detekt is wrong, that is a downcast to a subtype and should be always safe. Also the kotlin compiler does not report it AFAIK

Comment (pakoito) [inline compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt]: I did the strings wrong because I edited from web :trollface: I'll fix them later.

Comment (pakoito) [inline compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt]: The case for detekt may just be the order of the passes. I wouldn't worry and just add it because the overhead cost is null.

Comment (Takhion) [inline compile-time/src/main/java/kategory/higherkinds/HigherKindsFileGenerator.kt]: Isn't it because of type erasure, like that with `this as ${hk.kindName}<*>` it wouldn't complain?
Anyway we know it's fine so SUPPRESS ALL THE THINGS!

**Comment by pakoito** [comment]
WAIT! The unscaped strings aren't fixed. Please wait before merging!
